//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadingAndRetrievingImages.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;   //this namespace is to upload image

    public partial class Student
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is requird")]
        [DisplayName("Student Name")]
        public string Name { get; set; }


        [Required(ErrorMessage = "Class is requird")]
        [DisplayName("Student Class")]
        public int Standard { get; set; }


        [DisplayName("Choose Image")]
        public string ImagePath { get; set; }


        public HttpPostedFileBase ImageFile { get; set; }  //when i upload image from the file upload controller so to save the image in folder use  HttpPostedFileBase  this class
    }
}
