//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudAppWithImagesInMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Employe
    {
        public int Id { get; set; }


        [Required(ErrorMessage = "Name is required")]
        [DisplayName("Employee Name")]
        public string Name { get; set; }


        [Required(ErrorMessage = "Designation is required")]
        [DisplayName("Employee Designation")]
        public string Designation { get; set; }


        [DisplayName("Employee Image")]
        public string ImagePath { get; set; }


        public HttpPostedFileBase ImageFile { get; set; }
    }
}
